"""mahasiswa prodi

Revision ID: 30ade6127764
Revises: 
Create Date: 2020-09-21 11:11:50.084011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ade6127764'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama_prodi', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=230), nullable=False),
    sa.Column('tgl_lahir', sa.String(length=10), nullable=False),
    sa.Column('ibu', sa.String(length=230), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('created_ats', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('prodi_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['prodi_id'], ['prodis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mahasiswas_email'), 'mahasiswas', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mahasiswas_email'), table_name='mahasiswas')
    op.drop_table('mahasiswas')
    op.drop_table('prodis')
    # ### end Alembic commands ###
